// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqqxpdgnatumfelixxym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xcXhwZGduYXR1bWZlbGl4eHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Mjg5MTgsImV4cCI6MjA2MTQwNDkxOH0.P6KChXJhfxNPX0vflWGcdNJIG3PPKu_X5Py1qL4cUtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);